# angelOS wallpaper / dark — generated, edit templates/kitty.conf instead
foreground              #fafafa
background              #171a22
selection_foreground    #171a22
selection_background    #8d95ba
cursor                  #8d95ba
cursor_text_color       #171a22
cursor_trail_color      #b3b9d0
url_color               #b3b9d0
active_border_color     #8d95ba
inactive_border_color   #171a22
active_tab_foreground   #171a22
active_tab_background   #8d95ba
inactive_tab_foreground #b4b5b7
inactive_tab_background #1c1f2a
tab_bar_background      #171a22
color0  #171a22
color1  #e36b78
color2  #8eaf73
color3  #d8b56b
color4  #b3b9d0
color5  #8d95ba
color6  #72b7b0
color7  #fafafa
color8  #b4b5b7
color9  #f58b98
color10 #aacf93
color11 #efd18b
color12 #b3b9d0
color13 #8d95ba
color14 #92d7d0
color15 #fafafa
