# angelOS wallpaper / dark — generated, edit templates/kitty.conf instead
foreground              #fafafa
background              #171c22
selection_foreground    #171c22
selection_background    #8ab3b3
cursor                  #8ab3b3
cursor_text_color       #171c22
cursor_trail_color      #b1cccc
url_color               #b1cccc
active_border_color     #8ab3b3
inactive_border_color   #171c22
active_tab_foreground   #171c22
active_tab_background   #8ab3b3
inactive_tab_foreground #b4b5b7
inactive_tab_background #1c2429
tab_bar_background      #171c22
color0  #171c22
color1  #e36b78
color2  #8eaf73
color3  #d8b56b
color4  #b1cccc
color5  #8ab3b3
color6  #72b7b0
color7  #fafafa
color8  #b4b5b7
color9  #f58b98
color10 #aacf93
color11 #efd18b
color12 #b1cccc
color13 #8ab3b3
color14 #92d7d0
color15 #fafafa
