# angelOS wallpaper / dark — generated, edit templates/kitty.conf instead
foreground              #fafafa
background              #1a1a1f
selection_foreground    #1a1a1f
selection_background    #b59a8c
cursor                  #b59a8c
cursor_text_color       #1a1a1f
cursor_trail_color      #cdbbb2
url_color               #cdbbb2
active_border_color     #b59a8c
inactive_border_color   #1a1a1f
active_tab_foreground   #1a1a1f
active_tab_background   #b59a8c
inactive_tab_foreground #b4b5b7
inactive_tab_background #232023
tab_bar_background      #1a1a1f
color0  #1a1a1f
color1  #e36b78
color2  #8eaf73
color3  #d8b56b
color4  #cdbbb2
color5  #b59a8c
color6  #72b7b0
color7  #fafafa
color8  #b4b5b7
color9  #f58b98
color10 #aacf93
color11 #efd18b
color12 #cdbbb2
color13 #b59a8c
color14 #92d7d0
color15 #fafafa
