color0 #464741
color1 #ffb4ab
color2 #c5c8bc
color3 #c7c7c1
color4 #c1c8c7
color5 #c5c8bc
color6 #c7c7c1
color7 #e5e2e0
color8 #90918a
color9 #ffb4ab
color10 #c5c8bc
color11 #c7c7c1
color12 #c1c8c7
color13 #c5c8bc
color14 #c7c7c1
color15 #e5e2e0

cursor                #e5e2e0
cursor_text_color     #141312
background            #141312
foreground            #e5e2e0
selection_foreground  #c7c7be
selection_background  #464741
active_border_color   #c5c8bc
inactive_border_color #464741
url_color             #c5c8bc

active_tab_foreground   #2e3129
active_tab_background   #c5c8bc
inactive_tab_foreground #c7c7be
inactive_tab_background #464741
cursor_trail_color      #c7c7be
