.pragma library

// The Y2K helper angel, 30×40 art pixels (PxIcon bitmap + palette):
//   '#' outline  'l' halo  'y' hair  'h' hair shade  'f' skin  's' skin shade
//   'e' eyes  'w' dress  'g' dress shade  'o' lips, blush, sash, heels  'v' wings

const up = [
    "...........########...........",
    "..........#llllllll#..........",
    "...........########...........",
    "............######............",
    "..........##yyyyyy##..........",
    ".........#yyyhyyhyyy#.........",
    ".........#yhffffffhy#.........",
    ".........#yf##ff##fy#.........",
    ".........#yfewffwefy#.........",
    ".........#yfoffffofy#.........",
    ".........#yhffooffhy#.........",
    "..##.....#yyhffffhyy#.....##..",
    ".#vv#....#yhy#ff#yhy#....#vv#.",
    "#vvvv#.#yhy#ffffff#yhy#.#vvvv#",
    "#vvvvv##yhy#wwffww#yhy##vvvvv#",
    "#vvvvvv#yh#gwwwwwwg#hy#vvvvvv#",
    ".#vvvvv#yh#wwwwwwww#hy#vvvvv#.",
    "#vvvvvv#yhy#gwwwwg#yhy#vvvvvv#",
    ".#vgvvv#yhy#oooooo#yhy#vvvgv#.",
    "..#vgvv#yhy#gwwwwg#yhy#vvgv#..",
    "...#vgv#yh#gwwwwwwg#hy#vgv#...",
    "....#vv#y#gwwwwwwwwg#y#vv#....",
    ".....##.##gwwwwwwwwg##.##.....",
    ".........#wwwwwwwwfw#.........",
    ".........#wwwgwwwffw#.........",
    ".........#wwgwwwwfff#.........",
    ".........############.........",
    "..........#fff##fff#..........",
    "..........#fff##fff#..........",
    "..........#fff##fsf#..........",
    "...........#ff##ff#...........",
    "...........#fs##sf#...........",
    "...........#ff##ff#...........",
    "...........#ff##ff#...........",
    "...........#ff##ff#...........",
    "...........#ff##ff#...........",
    "...........#fs##sf#...........",
    "...........#oo##oo#...........",
    "..........#oo#..#oo#..........",
    "..........###....###.........."
];

const down = [
    "...........########...........",
    "..........#llllllll#..........",
    "...........########...........",
    "............######............",
    "..........##yyyyyy##..........",
    ".........#yyyhyyhyyy#.........",
    ".........#yhffffffhy#.........",
    ".........#yf##ff##fy#.........",
    ".........#yfewffwefy#.........",
    ".........#yfoffffofy#.........",
    ".........#yhffooffhy#.........",
    ".........#yyhffffhyy#.........",
    ".........#yhy#ff#yhy#.........",
    ".......#yhy#ffffff#yhy#.......",
    ".......#yhy#wwffww#yhy#.......",
    ".....###yh#gwwwwwwg#hy###.....",
    "....#vv#yh#wwwwwwww#hy#vv#....",
    "...#vvv#yhy#gwwwwg#yhy#vvv#...",
    "..#vvvv#yhy#oooooo#yhy#vvvv#..",
    ".#vvvvv#yhy#gwwwwg#yhy#vvvvv#.",
    "#vvvvvv#yh#gwwwwwwg#hy#vvvvvv#",
    "#vgvvvv#y#gwwwwwwwwg#y#vvvvgv#",
    "#vvgvv#.##gwwwwwwwwg##.#vvgvv#",
    ".#vvg#...#wwwwwwwwfw#...#gvv#.",
    "..###....#wwwgwwwffw#....###..",
    ".........#wwgwwwwfff#.........",
    ".........############.........",
    "..........#fff##fff#..........",
    "..........#fff##fff#..........",
    "..........#fff##fsf#..........",
    "...........#ff##ff#...........",
    "...........#fs##sf#...........",
    "...........#ff##ff#...........",
    "...........#ff##ff#...........",
    "...........#ff##ff#...........",
    "...........#ff##ff#...........",
    "...........#fs##sf#...........",
    "...........#oo##oo#...........",
    "..........#oo#..#oo#..........",
    "..........###....###.........."
];

const blink = [
    "...........########...........",
    "..........#llllllll#..........",
    "...........########...........",
    "............######............",
    "..........##yyyyyy##..........",
    ".........#yyyhyyhyyy#.........",
    ".........#yhffffffhy#.........",
    ".........#yhffffffhy#.........",
    ".........#yf##ff##fy#.........",
    ".........#yfoffffofy#.........",
    ".........#yhffooffhy#.........",
    "..##.....#yyhffffhyy#.....##..",
    ".#vv#....#yhy#ff#yhy#....#vv#.",
    "#vvvv#.#yhy#ffffff#yhy#.#vvvv#",
    "#vvvvv##yhy#wwffww#yhy##vvvvv#",
    "#vvvvvv#yh#gwwwwwwg#hy#vvvvvv#",
    ".#vvvvv#yh#wwwwwwww#hy#vvvvv#.",
    "#vvvvvv#yhy#gwwwwg#yhy#vvvvvv#",
    ".#vgvvv#yhy#oooooo#yhy#vvvgv#.",
    "..#vgvv#yhy#gwwwwg#yhy#vvgv#..",
    "...#vgv#yh#gwwwwwwg#hy#vgv#...",
    "....#vv#y#gwwwwwwwwg#y#vv#....",
    ".....##.##gwwwwwwwwg##.##.....",
    ".........#wwwwwwwwfw#.........",
    ".........#wwwgwwwffw#.........",
    ".........#wwgwwwwfff#.........",
    ".........############.........",
    "..........#fff##fff#..........",
    "..........#fff##fff#..........",
    "..........#fff##fsf#..........",
    "...........#ff##ff#...........",
    "...........#fs##sf#...........",
    "...........#ff##ff#...........",
    "...........#ff##ff#...........",
    "...........#ff##ff#...........",
    "...........#ff##ff#...........",
    "...........#fs##sf#...........",
    "...........#oo##oo#...........",
    "..........#oo#..#oo#..........",
    "..........###....###.........."
];

const talk = [
    "...........########...........",
    "..........#llllllll#..........",
    "...........########...........",
    "............######............",
    "..........##yyyyyy##..........",
    ".........#yyyhyyhyyy#.........",
    ".........#yhffffffhy#.........",
    ".........#yf##ff##fy#.........",
    ".........#yfewffwefy#.........",
    ".........#yfoffffofy#.........",
    ".........#yhfo##ofhy#.........",
    "..##.....#yyhffffhyy#.....##..",
    ".#vv#....#yhy#ff#yhy#....#vv#.",
    "#vvvv#.#yhy#ffffff#yhy#.#vvvv#",
    "#vvvvv##yhy#wwffww#yhy##vvvvv#",
    "#vvvvvv#yh#gwwwwwwg#hy#vvvvvv#",
    ".#vvvvv#yh#wwwwwwww#hy#vvvvv#.",
    "#vvvvvv#yhy#gwwwwg#yhy#vvvvvv#",
    ".#vgvvv#yhy#oooooo#yhy#vvvgv#.",
    "..#vgvv#yhy#gwwwwg#yhy#vvgv#..",
    "...#vgv#yh#gwwwwwwg#hy#vgv#...",
    "....#vv#y#gwwwwwwwwg#y#vv#....",
    ".....##.##gwwwwwwwwg##.##.....",
    ".........#wwwwwwwwfw#.........",
    ".........#wwwgwwwffw#.........",
    ".........#wwgwwwwfff#.........",
    ".........############.........",
    "..........#fff##fff#..........",
    "..........#fff##fff#..........",
    "..........#fff##fsf#..........",
    "...........#ff##ff#...........",
    "...........#fs##sf#...........",
    "...........#ff##ff#...........",
    "...........#ff##ff#...........",
    "...........#ff##ff#...........",
    "...........#ff##ff#...........",
    "...........#fs##sf#...........",
    "...........#oo##oo#...........",
    "..........#oo#..#oo#..........",
    "..........###....###.........."
];

// her own colours; AngelHelper may tint some of them (see there)
const palette = {
    "#": "#3b2340",
    "l": "#ffe07a",
    "y": "#ffd27a",
    "h": "#e2a452",
    "f": "#ffdccb",
    "s": "#efb2a2",
    "e": "#5f7dff",
    "w": "#ffffff",
    "g": "#d8cdef",
    "o": "#ff5f9e",
    "v": "#f6f2ff"
};
