.pragma library

// The first demon of the Y2K corner (Settings → Y2K → Looks → "Mini"), 20×21 art pixels in
// the Icons.js alphabet with the colours of that version (AngelHelper):
//   '#' ink  'x' hair and bat wings  'f' skin  'o' eyes  'r' horns, bow and tail  'w' dress
const up = [
    ".....#r......r#.....",
    ".....#rr....rr#.....",
    "......#rr##rr#......",
    ".......#xxxx#.......",
    "##....#xxxxxx#....##",
    "#x#..#xxxxxxxx#..#x#",
    "#xx##xffffffffx##xx#",
    "#xxx#xfoffffofx#xxx#",
    "#x#x#xffffffffx#x#x#",
    "#...#xfff#rfffx#...#",
    ".....xxffffffxx.....",
    "...##xx#rrrr#xx##...",
    "....#x#wwrrwww#x#...",
    "....#x#wwwwwwww#x#..",
    "...#x#wwwwwwwwww#x#.",
    "...#x#wrrwwwwrrw#x#.",
    "..#xx#wwwwwwwwww#xx#",
    "..####wwwwwwwwww###r",
    "......##########..#r",
    ".......#f#..#f#..#rr",
    ".......###..###....."
];
const down = [
    ".....#r......r#.....",
    ".....#rr....rr#.....",
    "......#rr##rr#......",
    ".......#xxxx#.......",
    "......#xxxxxx#......",
    ".....#xxxxxxxx#.....",
    "##..#xffffffffx#..##",
    "#x#.#xfoffffofx#.#x#",
    "#xx##xffffffffx##xx#",
    "#xxx#xfff#rfffx#xxx#",
    "#x#x#xxffffffxx#x#x#",
    "#...##x#rrrr#x##...#",
    "....#x#wwrrwww#x#...",
    "....#x#wwwwwwww#x#..",
    "...#x#wwwwwwwwww#x#.",
    "...#x#wrrwwwwrrw#x#.",
    "..#xx#wwwwwwwwww#xx#",
    "..####wwwwwwwwww###r",
    "......##########.#r.",
    ".......#f#..#f#..#rr",
    ".......###..###....."
];
const blink = [
    ".....#r......r#.....",
    ".....#rr....rr#.....",
    "......#rr##rr#......",
    ".......#xxxx#.......",
    "##....#xxxxxx#....##",
    "#x#..#xxxxxxxx#..#x#",
    "#xx##xffffffffx##xx#",
    "#xxx#xf##ff##fx#xxx#",
    "#x#x#xffffffffx#x#x#",
    "#...#xfff#rfffx#...#",
    ".....xxffffffxx.....",
    "...##xx#rrrr#xx##...",
    "....#x#wwrrwww#x#...",
    "....#x#wwwwwwww#x#..",
    "...#x#wwwwwwwwww#x#.",
    "...#x#wrrwwwwrrw#x#.",
    "..#xx#wwwwwwwwww#xx#",
    "..####wwwwwwwwww###r",
    "......##########..#r",
    ".......#f#..#f#..#rr",
    ".......###..###....."
];
const talk = [
    ".....#r......r#.....",
    ".....#rr....rr#.....",
    "......#rr##rr#......",
    ".......#xxxx#.......",
    "##....#xxxxxx#....##",
    "#x#..#xxxxxxxx#..#x#",
    "#xx##xffffffffx##xx#",
    "#xxx#xfoffffofx#xxx#",
    "#x#x#xffffffffx#x#x#",
    "#...#xff#rr#ffx#...#",
    ".....xxff##ffxx.....",
    "...##xx#rrrr#xx##...",
    "....#x#wwrrwww#x#...",
    "....#x#wwwwwwww#x#..",
    "...#x#wwwwwwwwww#x#.",
    "...#x#wrrwwwwrrw#x#.",
    "..#xx#wwwwwwwwww#xx#",
    "..####wwwwwwwwww###r",
    "......##########..#r",
    ".......#f#..#f#..#rr",
    ".......###..###....."
];
