# angelOS wallpaper / dark
[colors.primary]
background = '#1a1a1f'
foreground = '#fafafa'

[colors.cursor]
text = '#1a1a1f'
cursor = '#b59a8c'

[colors.vi_mode_cursor]
text = '#1a1a1f'
cursor = '#cdbbb2'

[colors.selection]
text = '#1a1a1f'
background = '#b59a8c'

[colors.search.matches]
foreground = '#1a1a1f'
background = '#cdbbb2'

[colors.search.focused_match]
foreground = '#1a1a1f'
background = '#b59a8c'

[colors.normal]
black   = '#1a1a1f'
red     = '#e36b78'
green   = '#8eaf73'
yellow  = '#d8b56b'
blue    = '#cdbbb2'
magenta = '#b59a8c'
cyan    = '#72b7b0'
white   = '#fafafa'

[colors.bright]
black   = '#b4b5b7'
red     = '#f58b98'
green   = '#aacf93'
yellow  = '#efd18b'
blue    = '#cdbbb2'
magenta = '#b59a8c'
cyan    = '#92d7d0'
white   = '#fafafa'
