# angelOS wallpaper / dark
[colors.primary]
background = '#171c22'
foreground = '#fafafa'

[colors.cursor]
text = '#171c22'
cursor = '#8ab3b3'

[colors.vi_mode_cursor]
text = '#171c22'
cursor = '#b1cccc'

[colors.selection]
text = '#171c22'
background = '#8ab3b3'

[colors.search.matches]
foreground = '#171c22'
background = '#b1cccc'

[colors.search.focused_match]
foreground = '#171c22'
background = '#8ab3b3'

[colors.normal]
black   = '#171c22'
red     = '#e36b78'
green   = '#8eaf73'
yellow  = '#d8b56b'
blue    = '#b1cccc'
magenta = '#8ab3b3'
cyan    = '#72b7b0'
white   = '#fafafa'

[colors.bright]
black   = '#b4b5b7'
red     = '#f58b98'
green   = '#aacf93'
yellow  = '#efd18b'
blue    = '#b1cccc'
magenta = '#8ab3b3'
cyan    = '#92d7d0'
white   = '#fafafa'
